apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-pull
  namespace: shop
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: nexus-pull
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "nexus:8082": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef: { key: nexus, property: username }
    - secretKey: password
      remoteRef: { key: nexus, property: password }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-api-secrets
  namespace: shop
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: order-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: ORDER_SIGNING_KEY
      remoteRef: { key: order-api, property: signing_key }